site_name: KinIn documentation
site_url: https://sitename.example
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
nav:
  - Home: index.md  # Link to the main page
  - Getting Started:
    - Installation: getting-started/installation.md
    - Usage: getting-started/usage.md
  - Modules:
    - Inverse Functions: Modules/InverseFunctions.md
    - Jacobian Functions: Modules/JacobianFunctions.md  # New module
    - Linear Algebra: Modules/linAlg.md 
  - Examples:
    - Example 1: examples/example1.md
  - About:
    - License: about/license.md