site_name: KinIn documentation
site_url: https://sitename.example
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  # Enable syntax highlighting with Pygments
  highlightjs: false
  hljs_languages: []

# Python Markdown extensions
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences

# Custom plugins
plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_config: "custom_extensions.structured_text_lexer:register_lexer"

# Extra CSS for custom styling
extra_css:
  - css/custom.css

nav:
  - Home: index.md  # Link to the main page
  - Getting Started:
    - Installation: getting-started/installation.md
  - Modules:
    - Linear Algebra: Modules/linAlg.md 
    - Inverse Functions: Modules/InverseFunctions.md
    - Jacobian Functions: Modules/JacobianFunctions.md  # New module

  - Examples:
    - Examples Linear Algebra: examples/Ex_Alg.md
    - Examples Inverse Functions: examples/Ex_Inv.md
    - Examples Jacobian Functions: examples/Ex_Jacobian.md
    - Example mechanism: examples/Ex_Mechanism.md
    - Matlab demonstration: examples/Ex_Matlab.md
  - About:
    - License: about/license.md